### ISSUE TITLE
conflicting plugin with slimefun

### ISSUE THREAD

**Issue by jordanwilliams1** [meiskam/PlayerHeads#15]
**Describe the bug**
Slime fun heads will break when you drop them if this plugin is installed.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Install Slimefun and CS-CORE lib.
2. Get a Slimefun 'HEAD' /SF CHEAT
3. Drop it on the floor, it breaks

**Expected behavior**
It should not break any heads. Tested on 1.13 & 1.14.4

**Comment by jordanwilliams1** [comment]
Here's my test server if you just want to do a quick test, Should speed it up for you.
https://mega.nz/#!kdtmkCjL!LFy3ouJS88Nryi575FU8tSV-Wva5qyfqcRcdooeRaxw

**Comment by crashdemons** [comment]
I will test this soon but I wanted to provide some more immediate support:

If you disable _fixdroppedheads_ then PlayerHeads will avoid automatically converting these heads when dropped as items. The downside of doing this is PlayerHeads custom heads will also not retain their name/lore when broken by pistons or water (but they will still be detected by right-clicks or API types).

However, this setting does not change the behavior when a head-block is broken. Head-block breaking attempts to determine if the head is a custom-head by it having no owner username.  If Slimefun sets a username for its custom heads, PH will assume it belongs to a player.

[I'm assuming at this time that this is the issue here, but I will need to confirm first.]

Obviously this is not ideal behavior, but the only way to avoid this really is for me to add a blacklist of head names/uuids from other plugins that PH should ignore.

**Comment by jordanwilliams1** [comment]
@crashdemons How do you disable fixdroppedheads? I Don't see a config option

**Comment by crashdemons** [comment]
Please try the following development build, which tries to ignore "CSCoreLib" heads when it encounters them.
(ignoring by UUID is not easily done, since each Slimefun item has a different UUID it seems - they are ignored by name instead)

https://ci.meme.tips/job/PlayerHeads-5.2/2/

**Comment by crashdemons** [comment]
> 
> 
> @crashdemons How do you disable fixdroppedheads? I Don't see a config option

you shouldn't need to with 5.2.3 but there should be a configuration option if your config is recent.  you can add it directly to the config as `fixdroppedheads: false`
or using `/ph config set fixedroppedheads false` ingame.

**Comment by crashdemons** [comment]
Let me know how testing goes with the new version when you have a chance.

Thanks.

**Comment by jordanwilliams1** [comment]
@crashdemons Yes it's fixed.

**Comment by crashdemons** [comment]
alright. marking as fixed by commits 3fcb0a84707e0f279bab779193909e52e45ed438 and 49b6b1214cecc38f34e77fabe1e46aa45a596221
