### ISSUE TITLE
Config wont work

### ISSUE THREAD

**Issue by Axeera** [meiskam/PlayerHeads#16]
I change settings in the config file and they wont change anything in game after.

**Comment by crashdemons** [comment]
did you reload the config with the command?

**Comment by Axeera** [comment]
I restarted the whole server and changed everything in the yml, but i have not used any commands in game. Only changed the files and restarted every time. Using the latest verision.

**Comment by crashdemons** [comment]
I'm not able to reproduce the issue with 5.2.3 or 5.2.5 on a 1.15.1 server.

I can use the `/ph config set ...` to change droprates and other settings, and it is reflected by ingame behavior.

I can change the file directly while the server is running and use `/ph config reload` to see the changes reflected ingame.

What can't be done though is changing the file while the server is running and restart the server, since this will cause the plugin to save any possible ingame changes (like with `ph config set ...`), overwriting the file.  A `ph config reload` must be performed if you want to change it from the file while the server is running.

If you've done that and you still have issues, then there may be a formatting issue with your YML file. pasting it into the following website will let you know if this is the case: http://www.yamllint.com/

**Comment by Axeera** [comment]
thanks got it to work now, did not know i had to reload it, all other plugins work by restarting the server.
