### ISSUE TITLE
Data not auto updating

### ISSUE THREAD

**Issue by MCTyler** [meiskam/PlayerHeads#6]
The Head data is not surviving a reboot and I must click on the Shops in order to reload the data and players to be able to sell the heads...We need a update...I will be willing to donate!

**Comment by crashdemons** [comment]
Let me know if you still have this issue with a recent version (3.12/3.12.13/4.x).

Note: the referenced commit above can be ignored, it was from another fork and is not relevant to this issue.

**Comment by crashdemons** [comment]
This issue is for an older version and there is insufficient information [about the server, the version of plugin, what shop plugin is being used, etc] to be able to debug this.

If you have the same problem again with newer versions, please open a new issue including the following information:

- The server version
- the playerheads version
- the other plugins relevant to the issue
- what you tried to do, what you expected it to do and what it did instead
